# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kylir Horton
email: kylirh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The personal website of Kylir Horton - Developer, photographer, and tech enthusiast.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kylir.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kylir
github_username: kylirh

# Build settings
markdown: kramdown
theme: minima
future: false
strict_front_matter: true
livereload: true

# Site structure
collections:
  projects:
    output: true
    permalink: /projects/:name/
  photography:
    output: true
    permalink: /photography/:name/

# Default settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "photography"
    values:
      layout: "photo"
  - scope:
      path: ""
    values:
      layout: "default"

# SEO settings
lang: en_US
social:
  name: Kylir Horton
  links:
    - https://twitter.com/kylir
    - https://github.com/kylirh

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
